#coding: utf-8

codes = {"Австралия": "AU",
"Австрия": "AT",
"Азербайджан": "AZ",
"Аландские острова": "AX",
"Албания": "AL",
"Алжир": "DZ",
"Виргинские Острова (США)": "VI",
"Американское Самоа": "AS",
"Ангилья": "AI",
"Ангола": "AO",
"Андорра": "AD",
"Антарктида": "AQ",
"Антигуа и Барбуда": "AG",
"Аргентина": "AR",
"Армения": "AM",
"Аруба": "AW",
"Афганистан": "AF",
"Багамы": "BS",
"Бангладеш": "BD",
"Барбадос": "BB",
"Бахрейн": "BH",
"Белиз": "BZ",
"Белоруссия": "BY",
"Бельгия": "BE",
"Бенин": "BJ",
"Бермуды": "BM",
"Болгария": "BG",
"Боливия": "BO",
"Бонэйр.  Синт-Эстатиус и Саба": "BQ",
"Босния и Герцеговина": "BA",
"Ботсвана": "BW",
"Бразилия": "BR",
"Британская территория в Индийском океане": "IO",
"Виргинские Острова (Великобритания)": "VG",
"Бруней": "BN",
"Буркина-Фасо": "BF",
"Бурунди": "BI",
"Бутан": "BT",
"Вануату": "VU",
"Ватикан": "VA",
"Великобритания": "GB",
"Венгрия": "HU",
"Венесуэла": "VE",
"Внешние малые острова (США)": "UM",
"Восточный Тимор": "TL",
"Вьетнам": "VN",
"Габон": "GA",
"Гаити": "HT",
"Гайана": "GY",
"Гамбия": "GM",
"Гана": "GH",
"Гваделупа": "GP",
"Гватемала": "GT",
"Гвиана": "GF",
"Гвинея": "GN",
"Гвинея-Бисау": "GW",
"Германия": "DE",
"Гернси": "GG",
"Гибралтар": "GI",
"Гондурас": "HN",
"Гонконг": "HK",
"Гренада": "GD",
"Гренландия": "GL",
"Греция": "GR",
"Грузия": "GE",
"Гуам": "GU",
"Дания": "DK",
"Джерси": "JE",
"Джибути": "DJ",
"Доминика": "DM",
"Доминиканская Республика": "DO",
"Демократическая Республика Конго": "CD",
"Европейский союз": "EU",
"Египет": "EG",
"Замбия": "ZM",
"САДР": "EH",
"Зимбабве": "ZW",
"Израиль": "IL",
"Индия": "IN",
"Индонезия": "ID",
"Иордания": "JO",
"Ирак": "IQ",
"Иран": "IR",
"Ирландия": "IE",
"Исландия": "IS",
"Испания": "ES",
"Италия": "IT",
"Йемен": "YE",
"Кабо-Верде": "CV",
"Казахстан": "KZ",
"Острова Кайман": "KY",
"Камбоджа": "KH",
"Камерун": "CM",
"Канада": "CA",
"Катар": "QA",
"Кения": "KE",
"Кипр": "CY",
"Киргизия": "KG",
"Кирибати": "KI",
"Китайская Республика": "TW",
"КНДР (Корейская Народно-Демократическая Республика)": "KP",
"КНР (Китайская Народная Республика)": "CN",
"Кокосовые острова": "CC",
"Колумбия": "CO",
"Коморы": "KM",
"Коста-Рика": "CR",
"Кот-д’Ивуар": "CI",
"Куба": "CU",
"Кувейт": "KW",
"Кюрасао": "CW",
"Лаос": "LA",
"Латвия": "LV",
"Лесото": "LS",
"Либерия": "LR",
"Ливан": "LB",
"Ливия": "LY",
"Литва": "LT",
"Лихтенштейн": "LI",
"Люксембург": "LU",
"Маврикий": "MU",
"Мавритания": "MR",
"Мадагаскар": "MG",
"Майотта": "YT",
"Макао": "MO",
"Македония": "MK",
"Малави": "MW",
"Малайзия": "MY",
"Мали": "ML",
"Мальдивы": "MV",
"Мальта": "MT",
"Марокко": "MA",
"Мартиника": "MQ",
"Маршалловы Острова": "MH",
"Мексика": "MX",
"Микронезия": "FM",
"Мозамбик": "MZ",
"Молдавия": "MD",
"Монако": "MC",
"Монголия": "MN",
"Монтсеррат": "MS",
"Мьянма": "MM",
"Намибия": "nan",
"Науру": "NR",
"Непал": "NP",
"Нигер": "NE",
"Нигерия": "NG",
"Нидерланды": "NL",
"Никарагуа": "NI",
"Ниуэ": "NU",
"Новая Зеландия": "NZ",
"Новая Каледония": "NC",
"Норвегия": "NO",
"ОАЭ": "AE",
"Оман": "OM",
"Остров Буве": "BV",
"Остров Мэн": "IM",
"Острова Кука": "CK",
"Остров Норфолк": "NF",
"Остров Рождества": "CX",
"Острова Питкэрн": "PN",
"Острова Святой Елены.  Вознесения и Тристан-да-Кунья": "SH",
"Пакистан": "PK",
"Палау": "PW",
"Государство Палестина": "PS",
"Панама": "PA",
"Папуа — Новая Гвинея": "PG",
"Парагвай": "PY",
"Перу": "PE",
"Польша": "PL",
"Португалия": "PT",
"Пуэрто-Рико": "PR",
"Республика Конго": "CG",
"Республика Корея": "KR",
"Реюньон": "RE",
"Россия": "RU",
"Руанда": "RW",
"Румыния": "RO",
"Сальвадор": "SV",
"Самоа": "WS",
"Сан-Марино": "SM",
"Сан-Томе и Принсипи": "ST",
"Саудовская Аравия": "SA",
"Свазиленд": "SZ",
"Северные Марианские Острова": "MP",
"Сейшельские Острова": "SC",
"Сен-Бартелеми": "BL",
"Сен-Мартен": "MF",
"Сен-Пьер и Микелон": "PM",
"Сенегал": "SN",
"Сент-Винсент и Гренадины": "VC",
"Сент-Китс и Невис": "KN",
"Сент-Люсия": "LC",
"Сербия": "RS",
"Сингапур": "SG",
"Синт-Мартен": "SX",
"Сирия": "SY",
"Словакия": "SK",
"Словения": "SI",
"Соломоновы Острова": "SB",
"Сомали": "SO",
"Судан": "SD",
"СССР (до сентября 1992 года)": "SU",
"Суринам": "SR",
"США": "US",
"Сьерра-Леоне": "SL",
"Таджикистан": "TJ",
"Таиланд": "TH",
"Танзания": "TZ",
"Тёркс и Кайкос": "TC",
"Того": "TG",
"Токелау": "TK",
"Тонга": "TO",
"Тринидад и Тобаго": "TT",
"Тувалу": "TV",
"Тунис": "TN",
"Туркмения": "TM",
"Турция": "TR",
"Уганда": "UG",
"Узбекистан": "UZ",
"Украина": "UA",
"Уоллис и Футуна": "WF",
"Уругвай": "UY",
"Фареры": "FO",
"Фиджи": "FJ",
"Филиппины": "PH",
"Финляндия": "FI",
"Фолклендские острова": "FK",
"Франция": "FR",
"Французская Полинезия": "PF",
"Французские Южные и Антарктические Территории": "TF",
"Херд и Макдональд": "HM",
"Хорватия": "HR",
"ЦАР": "CF",
"Чад": "TD",
"Черногория": "ME",
"Чехия": "CZ",
"Чили": "CL",
"Швейцария": "CH",
"Швеция": "SE",
"Шпицберген и Ян-Майен": "SJ",
"Шри-Ланка": "LK",
"Эквадор": "EC",
"Экваториальная Гвинея": "GQ",
"Эритрея": "ER",
"Эстония": "EE",
"Эфиопия": "ET",
"ЮАР": "ZA",
"Южная Георгия и Южные Сандвичевы Острова": "GS",
"Южный Судан": "SS",
"Ямайка": "JM",
"Япония": "JP",
}


eng_codes = {
'AF':'Afghanistan',
'AX':'Åland Islands',
'AL':'Albania',
'DZ':'Algeria',
'AS':'American Samoa',
'AD':'Andorra',
'AO':'Angola',
'AI':'Anguilla',
'AQ':'Antarctica',
'AG':'Antigua and Barbuda',
'AR':'Argentina',
'AM':'Armenia',
'AW':'Aruba',
'AU':'Australia',
'AT':'Austria',
'AZ':'Azerbaijan',
'BS':'Bahamas',
'BH':'Bahrain',
'BD':'Bangladesh',
'BB':'Barbados',
'BY':'Belarus',
'BE':'Belgium',
'BZ':'Belize',
'BJ':'Benin',
'BM':'Bermuda',
'BT':'Bhutan',
'BO':'Bolivia, Plurinational State of',
'BQ':'Bonaire, Sint Eustatius and Saba',
'BA':'Bosnia and Herzegovina',
'BW':'Botswana',
'BV':'Bouvet Island',
'BR':'Brazil',
'IO':'British Indian Ocean Territory',
'BN':'Brunei Darussalam',
'BG':'Bulgaria',
'BF':'Burkina Faso',
'BI':'Burundi',
'KH':'Cambodia',
'CM':'Cameroon',
'CA':'Canada',
'CV':'Cape Verde',
'KY':'Cayman Islands',
'CF':'Central African Republic',
'TD':'Chad',
'CL':'Chile',
'CN':'China',
'CX':'Christmas Island',
'CC':'Cocos (Keeling) Islands',
'CO':'Colombia',
'KM':'Comoros',
'CG':'Congo',
'CD':'Congo, the Democratic Republic of the',
'CK':'Cook Islands',
'CR':'Costa Rica',
'CI':"Côte d'Ivoire",
'HR':'Croatia',
'CU':'Cuba',
'CW':'Curaçao',
'CY':'Cyprus',
'CZ':'Czech Republic',
'DK':'Denmark',
'DJ':'Djibouti',
'DM':'Dominica',
'DO':'Dominican Republic',
'EC':'Ecuador',
'EG':'Egypt',
'SV':'El Salvador',
'GQ':'Equatorial Guinea',
'ER':'Eritrea',
'EE':'Estonia',
'ET':'Ethiopia',
'FK':'Falkland Islands (Malvinas)',
'FO':'Faroe Islands',
'FJ':'Fiji',
'FI':'Finland',
'FR':'France',
'GF':'French Guiana',
'PF':'French Polynesia',
'TF':'French Southern Territories',
'GA':'Gabon',
'GM':'Gambia',
'GE':'Georgia',
'DE':'Germany',
'GH':'Ghana',
'GI':'Gibraltar',
'GR':'Greece',
'GL':'Greenland',
'GD':'Grenada',
'GP':'Guadeloupe',
'GU':'Guam',
'GT':'Guatemala',
'GG':'Guernsey',
'GN':'Guinea',
'GW':'Guinea-Bissau',
'GY':'Guyana',
'HT':'Haiti',
'HM':'Heard Island and McDonald Islands',
'VA':'Holy See (Vatican City State)',
'HN':'Honduras',
'HK':'Hong Kong',
'HU':'Hungary',
'IS':'Iceland',
'IN':'India',
'ID':'Indonesia',
'IR':'Iran, Islamic Republic of',
'IQ':'Iraq',
'IE':'Ireland',
'IM':'Isle of Man',
'IL':'Israel',
'IT':'Italy',
'JM':'Jamaica',
'JP':'Japan',
'JE':'Jersey',
'JO':'Jordan',
'KZ':'Kazakhstan',
'KE':'Kenya',
'KI':'Kiribati',
'KP':"Korea, Democratic People's Republic of",
'KR':'Korea, Republic of',
'KW':'Kuwait',
'KG':'Kyrgyzstan',
'LA':"Lao People's Democratic Republic",
'LV':'Latvia',
'LB':'Lebanon',
'LS':'Lesotho',
'LR':'Liberia',
'LY':'Libya',
'LI':'Liechtenstein',
'LT':'Lithuania',
'LU':'Luxembourg',
'MO':'Macao',
'MK':'Macedonia, the Former Yugoslav Republic of',
'MG':'Madagascar',
'MW':'Malawi',
'MY':'Malaysia',
'MV':'Maldives',
'ML':'Mali',
'MT':'Malta',
'MH':'Marshall Islands',
'MQ':'Martinique',
'MR':'Mauritania',
'MU':'Mauritius',
'YT':'Mayotte',
'MX':'Mexico',
'FM':'Micronesia, Federated States of',
'MD':'Moldova, Republic of',
'MC':'Monaco',
'MN':'Mongolia',
'ME':'Montenegro',
'MS':'Montserrat',
'MA':'Morocco',
'MZ':'Mozambique',
'MM':'Myanmar',
'nan':'Namibia',
'NR':'Nauru',
'NP':'Nepal',
'NL':'Netherlands',
'NC':'New Caledonia',
'NZ':'New Zealand',
'NI':'Nicaragua',
'NE':'Niger',
'NG':'Nigeria',
'NU':'Niue',
'NF':'Norfolk Island',
'MP':'Northern Mariana Islands',
'NO':'Norway',
'OM':'Oman',
'PK':'Pakistan',
'PW':'Palau',
'PS':'Palestine, State of',
'PA':'Panama',
'PG':'Papua New Guinea',
'PY':'Paraguay',
'PE':'Peru',
'PH':'Philippines',
'PN':'Pitcairn',
'PL':'Poland',
'PT':'Portugal',
'PR':'Puerto Rico',
'QA':'Qatar',
'RE':'Réunion',
'RO':'Romania',
'RU':'Russia',
'RW':'Rwanda',
'BL':'Saint Barthélemy',
'SH':'Saint Helena, Ascension and Tristan da Cunha',
'KN':'Saint Kitts and Nevis',
'LC':'Saint Lucia',
'MF':'Saint Martin (French part)',
'PM':'Saint Pierre and Miquelon',
'VC':'Saint Vincent and the Grenadines',
'WS':'Samoa',
'SM':'San Marino',
'ST':'Sao Tome and Principe',
'SA':'Saudi Arabia',
'SN':'Senegal',
'RS':'Serbia',
'SC':'Seychelles',
'SL':'Sierra Leone',
'SG':'Singapore',
'SX':'Sint Maarten (Dutch part)',
'SK':'Slovakia',
'SI':'Slovenia',
'SB':'Solomon Islands',
'SO':'Somalia',
'ZA':'South Africa',
'GS':'South Georgia and the South Sandwich Islands',
'SS':'South Sudan',
'ES':'Spain',
'LK':'Sri Lanka',
'SD':'Sudan',
'SR':'Suriname',
'SJ':'Svalbard and Jan Mayen',
'SZ':'Swaziland',
'SE':'Sweden',
'CH':'Switzerland',
'SY':'Syrian Arab Republic',
'TW':'Taiwan, Province of China',
'TJ':'Tajikistan',
'TZ':'Tanzania, United Republic of',
'TH':'Thailand',
'TL':'Timor-Leste',
'TG':'Togo',
'TK':'Tokelau',
'TO':'Tonga',
'TT':'Trinidad and Tobago',
'TN':'Tunisia',
'TR':'Turkey',
'TM':'Turkmenistan',
'TC':'Turks and Caicos Islands',
'TV':'Tuvalu',
'UG':'Uganda',
'UA':'Ukraine',
'AE':'United Arab Emirates',
'GB':'United Kingdom',
'US':'United States',
'UM':'United States Minor Outlying Islands',
'UY':'Uruguay',
'UZ':'Uzbekistan',
'VU':'Vanuatu',
'VE':'Venezuela, Bolivarian Republic of',
'VN':'Viet Nam',
'VG':'Virgin Islands, British',
'VI':'Virgin Islands, U.S.',
'WF':'Wallis and Futuna',
'EH':'Western Sahara',
'YE':'Yemen',
'ZM':'Zambia',
'ZW':'Zimbabwe',
}


